# NulFontPackager Sample Config File.
# Copyright (C) NulStudio 2014-2024. All rights reserved.

version: 1

fonts:
  workspaces:
    - 'F:\Movies\Boku no Kokoro no Yabai Yatsu S1+S2\Fonts'
  additional-fonts:

process:
  workspace: 'F:\Movies\Boku no Kokoro no Yabai Yatsu S1+S2'
  targets:
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 01 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [01][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 01.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 02 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [02][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 02.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 03 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [03][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 03.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 04 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [04][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 04.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 05 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [05][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 05.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 06 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [06][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 06.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 07 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [07][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 07.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 08 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [08][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 08.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 09 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [09][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 09.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 10 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [10][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 10.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 11 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [11][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 11.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 12 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [12][WebRip].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 12.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 12.5 [ Twi-Yaba ] (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [Twi-Yaba][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 12.5.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 13 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [13][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 13.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 14 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [14][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 14.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 15 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [15][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 15.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 16 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [16][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 16.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 17 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [17][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 17.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 18 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [18][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 18.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 19 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [19][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 19.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 20 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [20][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 20.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 21 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [21][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 21.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 22 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [22][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 22.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 23 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [23][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 23.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 24 (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [24][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 24.mkv'
    - media: '[Moozzi2] Boku no Kokoro no Yabai Yatsu - 25 END (BD 1920x1080 HEVC-YUV444P10 FLAC).mkv'
      subtitle: '[Nekomoe kissaten] Boku no Kokoro no Yabai Yatsu [25][Web].JPSC.ass'
      output: 'Boku no Kokoro no Yabai Yatsu - 25.mkv'
  options:
    aac: false